version: '2'

services:
  mysql01:
    image: mysql:5.7
    ports:
      - '13306:13306'
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  mysql02:
    image: mysql:5.7
    ports:
      - '23306:23306'
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  embulk_digdag:
    build:
      context: ./docker
    volumes:
      - ./src/:/workspace
    links:
      - mysql01
      - mysql02
